---
title: "R Notebook - Project 1"
output: html_Project1
---
###Libraries used
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape2)

###reading in data Beers.csv and Breweries.csv
Beers = read.csv(file.choose(),header = TRUE)
Breweries = read.csv(file.choose(),header = TRUE)

###Analysis Q1 - How many breweries are present in each state

# Combined data set is grouped sorted by amount of brewries in each state
Breweries %>% 
group_by(State) %>% 
summarize(count = n() )%>% 
arrange(desc(count))%>% 
print(n=51)

## The most breweries are Colorado (47), California (39) and Michigan (32). The fewest breweries are in DC, North Dakota, South Dakota and West Viginia (1 each).


###Analysis Q2 - Merging Beweries and Beers data and printing first and last 6 observations

#data sets are combined  on common variable Brewery ID
BeersBreweries=merge(Beers,Breweries,by.x = "Brewery_id",by.y = "Brew_ID")
colnames(BeersBreweries)[2]<- "Beer Name"
colnames(BeersBreweries)[8]<- "Brewery Name"
head(BeersBreweries,n=6)
tail(BeersBreweries,n=6)

###Analysis Q3- Missing values (NA's analysis)

#Finding miss values in the entire data set
is.na(BeersBreweries)

#replacing Blank Values with NAs
BeersBreweries [BeersBreweries==""]<- NA
apply(is.na(BeersBreweries),2,sum)


MissingIBU <- BeersBreweries %>% filter(is.na(IBU))
MissingABV <- BeersBreweries %>% filter(is.na(ABV))
MissingStyle <- BeersBreweries %>% filter(is.na(Style))
IBUClean <-BeersBreweries %>% filter(!is.na(IBU))
ABVClean <- BeersBreweries %>% filter(!is.na(ABV))

#Analysis Q4 - Compute median alcohol content and IBU for each state. Bar Chart
IBUCleanSummary<-IBUClean %>% 
group_by(State) %>% 
summarize(medianIBU = median(IBU) )%>% 
arrange(desc(medianIBU))%>% 
print(n=51)

ABVCleanSummary<-ABVClean %>% 
group_by(State) %>% 
summarize(medianABV = median(ABV)*1000 )%>% 
arrange(desc(medianABV))%>% 
print(n=51)


MedianComp=merge(ABVCleanSummary,IBUCleanSummary,by = "State")
MedianComp<- MedianComp[c(1,3,2)]
MedianComp<-MedianComp[order(MedianComp$medianIBU),]
MedianCompMelt <- melt(MedianComp, id.vars = 'State')

ggplot(MedianCompMelt, aes(x= reorder(State, -value), y=value, fill=variable))+
  geom_bar(stat='identity', position='dodge')+
   scale_y_continuous(
    "MedianIBU",
    sec.axis = sec_axis(~ . * .001, name = "MedianABV")
  )

#Analysis Q5 - State with max ABV and max IBU
IBUCleanSummary2<-IBUClean %>% 
group_by(State) %>% 
summarize(medianIBU = median(IBU) )%>% 
arrange(desc(medianIBU))%>% 
print(n=51)

ABVCleanSummary2<-ABVClean %>% 
group_by(State) %>% 
summarize(medianABV = median(ABV) )%>% 
arrange(desc(medianABV))%>% 
print(n=51)

IBUClean2<-IBUClean[order(-IBUClean$IBU),]
ABVClean2<-ABVClean[order(-ABVClean$ABV),]

#Analysis Q6 - Summary Statistics and distribution of ABV

summary(BeersBreweries)

#Analysis Q7 - Relationship + scatter plot IBU vs. ABV

IBUABVClean <-ABVClean %>% filter(!is.na(IBU))

IBUABVClean %>% 
ggplot(mapping = aes(x = ABV, y = IBU)) +
geom_point()


fit <- lm(IBU ~ ABV, data = IBUABVClean)
summary(fit)
confint(fit, level = 0.95)

#Analysis Q8 -KNN IBU/ABV Ale vs IPA

IBUABVClean$IPAle = NA
IBUABVClean$IPAle[grepl("ale",IBUABVClean$Style,ignore.case=TRUE)] = "Ale"
IBUABVClean$IPAle[grepl("*ipa",IBUABVClean$Style,ignore.case=TRUE)] = "IPA"

IBUABVClean %>% 
group_by(IPAle) %>% 
summarize(count = n() )



IBUABVCleanScaled = data.frame(ZIBU = scale(IBUABVClean$IBU), ZABV = scale(IBUABVClean$ABV), IPAle = IBUABVClean$IPAle)
IBUABVCleanScaled <-IBUABVCleanScaled %>% filter(!is.na(IPAle))

classifications = knn.cv(IBUABVCleanScaled[,1:2], IBUABVCleanScaled$IPAle, k = 3)
confusionMatrix(table(classifications,IBUABVCleanScaled$IPAle))
####

iterations = 100

masterAcc = matrix(nrow = iterations)

splitPerc = .7 #Training / Test split Percentage

for(j in 1:iterations)
{
  
  trainIndices = sample(1:dim(IBUABVClean)[1],round(splitPerc * dim(IBUABVClean)[1]))
  train = IBUABVCleanScaled[trainIndices,]
  test = IBUABVCleanScaled[-trainIndices,]
  
  model = naiveBayes(train[,c(1,2)],as.factor(train$IPAle),laplace = 1)
  table(predict(model,test[,c(1,2)]),as.factor(test$IPAle))
  CM = confusionMatrix(table(predict(model,test[,c(1,2)]),as.factor(test$IPAle)))
  masterAcc[j] = CM$overall[1]
}

MeanAcc = colMeans(masterAcc)

MeanAcc

#9 Freestyle
StyleClean <- BeersBreweries %>% filter(!is.na(Style)) 

theText = unlist(str_split(str_replace_all(StyleClean$Style,"[^[:alnum:] ]", ""), boundary("word")))
sort(table(theText), decreasing=T)

StyleClean$IPAle = NA
StyleClean$IPAle[grepl("ale",StyleClean$Style,ignore.case=TRUE)] = "Ale"
StyleClean$IPAle[grepl("*ipa",StyleClean$Style,ignore.case=TRUE)] = "IPA"
StyleClean$IPAle[grepl("lager",StyleClean$Style,ignore.case=TRUE)] = "Lager"
StyleClean$IPAle[grepl("stout",StyleClean$Style,ignore.case=TRUE)] = "Stout"
StyleClean$IPAle[grepl("porter",StyleClean$Style,ignore.case=TRUE)] = "Porter"
StyleClean$IPAle[grepl("pilsener|pilsner",StyleClean$Style,ignore.case=TRUE)] = "Pilsener"
StyleClean$IPAle[grepl("beer",StyleClean$Style,ignore.case=TRUE)] = "Other Beer"
StyleClean$IPAle[grepl("fruit",StyleClean$Style,ignore.case=TRUE)] = "Fruit"
StyleClean$IPAle[grepl("witbier",StyleClean$Style,ignore.case=TRUE)] = "Witbier"
StyleClean$IPAle[grepl("kölsch|hefeweizen|märzen|oktoberfest|berliner|weissbier|altbier",StyleClean$Style,ignore.case=TRUE)] = "German Bier"
StyleClean$IPAle[grepl("cider",StyleClean$Style,ignore.case=TRUE)] = "Cider"
StyleClean$IPAle[grepl("bitter",StyleClean$Style,ignore.case=TRUE)] = "Bitter"

StyleClean %>% 
group_by(IPAle) %>% 
summarize(count = n() )

FindMoreTypes <- StyleClean %>% filter(is.na(IPAle)) 
theText2 = unlist(str_split(str_replace_all(FindMoreTypes$Style,"[^[:alnum:] ]", ""), boundary("word")))
sort(table(theText2), decreasing=T)

TotalCount<-StyleClean %>% 
group_by(IPAle, State) %>% 
summarize(count = n())



#Finding the  Top Style beer for each state
TotalCountbyStatePer<-TotalCount%>% group_by(State) %>% mutate(percent = count/sum(count))
TotalCountbyStatePer<-TotalCountbyStatePer[order(TotalCountbyStatePer$State),]
TotalCountbyStatePer%>% print(n = 100)
TotalCountbyStatePer$State <-as.character(TotalCountbyStatePer$State)
TotalCountbyStatePer$State  <- gsub('\\s+', '',  TotalCountbyStatePer$State )

p4 <- ggplot(data=TotalCountbyStatePer, aes(x="", y = percent, fill=IPAle)) + geom_bar(stat = "identity", position = position_fill()) +
coord_polar(theta = "y") +
    facet_wrap(~ State)  +
  theme(axis.title.x = element_blank(),
  axis.title.y = element_blank(), 
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  panel.grid  = element_blank()) + 
    theme(legend.position='bottom') 




TopTotalCountbyStatePer<-TotalCountbyStatePer%>%group_by(State)%>% filter(percent == max(percent)) %>% filter(1:n() == 1)


library(maps)
library(mapproj)
us_states <- map_data("state")
head(us_states)

state_abbs <- tibble(state = str_to_lower(state.name), abb = state.abb)

TopTotalCountbyStatePer2=merge(TopTotalCountbyStatePer,state_abbs,by.x = "State",by.y = "abb")
TotalCountbyStatePerMap <- left_join(us_states, TopTotalCountbyStatePer2, c("region"="state"))

p <- ggplot(data = TotalCountbyStatePerMap,
            aes(x = long, y = lat,
                group = group, fill = IPAle))

p + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) 
    
# Finding/mapping the states each style is the most popular in 

TotalCountbyStylePer<-TotalCount%>% group_by(IPAle) %>% mutate(percent = count/sum(count))
TotalCountbyStylePer<-TotalCountbyStylePer[order(TotalCountbyStylePer$IPAle),]
TotalCountbyStylePer%>% print(n = 100)
TotalCountbyStylePer$State <-as.character(TotalCountbyStylePer$State)
TotalCountbyStylePer$State  <- gsub('\\s+', '',  TotalCountbyStylePer$State )

#Mapping Ale
TotalCountbyStylePerAle <-TotalCountbyStylePer%>%filter (IPAle == "Ale")

TotalCountbyStylePerAle=merge(TotalCountbyStylePerAle,state_abbs,by.x = "State",by.y = "abb")
TotalCountbyStylePerAleMap <- left_join(us_states, TotalCountbyStylePerAle, c("region"="state"))

p2 <- ggplot(data = TotalCountbyStylePerAleMap,
            aes(x = long, y = lat,
                group = group, fill = percent))

p2 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) 
    
#Mapping IPA

TotalCountbyStylePerIPA <-TotalCountbyStylePer%>%filter (IPAle == "IPA")

TotalCountbyStylePerIPA=merge(TotalCountbyStylePerIPA,state_abbs,by.x = "State",by.y = "abb")
TotalCountbyStylePerIPAMap <- left_join(us_states, TotalCountbyStylePerIPA, c("region"="state"))

p3 <- ggplot(data = TotalCountbyStylePerIPAMap,
            aes(x = long, y = lat,
                group = group, fill = percent))

p3 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) 
